server:
  port: 9000
#  ssl:
#    key-store: classpath:qingpingyue.top.jks
#    key-store-password: qingpingyue
#    key-store-type: JKS
spring:
  #应用
  application:
    name: xingzhiblog-article
  #数据库
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xingzhiblog_article?useUnicode=true&characterEncoding=UTF-8&serverTimezone = Asia/Shanghai
    username: root
    password: root
    # 远程
#    username: mini_blog
#    password: xingzhiblog
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  devtools:
#    restart:
#      enabled: true  #设置开启热部署
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间（负数表示没限制）
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: xingzhiblog-article-fescar-service-group
  main:
    allow-bean-definition-overriding: true
  cache:
    type: redis
  rabbitmq:
    host: xxxxxx #TODO 地址改
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
#dubbo:
#  application:
#    name: dubbo-xingzhiblog-article
#  scan:
#    base-packages: com.xingzhi.xingzhiblog.article.service
#  # 设置超时时间
#  consumer:
#    timeout: 4000
#  protocol:
#    name: dubbo
#    port: 20881
#  registry:
#    address: nacos://localhost:8848
#  cloud:
#    subscribed-services: dubbo-xingzhiblog-user

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xingzhi.xingzhiblog.article.domain
# 日志配置
#logging:
#  level:
#    com.xingzhi: debug
#    org.springframework: WARN
#    org.spring.springboot.dao: debug
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40c{1.} [%X{user}] : %m%n%xwEx"
#  file:
#    path: /log/xingzhiblog.log

#pageHelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

xingzhiblog:
  thread:
    coreSize: 20
    maxSize: 100
    keepAliveTime: 30

debug: true